apiVersion: v1
name: techtrends
description: Helm chart for the TechTrends Flask application
keywords:
  - techtrends
version: 1.0.0
maintainers:
  - name: Sebastien Henry
    email: henry.sebastien1982@gmail.com
